#----------- Custom Variable Configurations -------------------
APPLICATION:
  MAILING:
    ACCOUNT:
      ACTIVATION_URL: http://localhost:8080/api/v1/auth/activate-account
      USERNAME: yash.11717121@gmail.com
      PASSWORD:
  SECURITY:
    JWT_EXPIRATION: 604800000
    JWT_SECRET:
  DATABASE:
    USERNAME: root
    PASSWORD:
    URL: jdbc:mysql://localhost:3306/lib_mng_sys
  HIBERNATE:
    SHOW_SQL: true
    FORMAT_SQL: true